### ISSUE TITLE
License and Confluent Hub

### ISSUE THREAD

**Issue by christian-edelsbrunner** [yashmayya/kafka-connect-transform-bytes-to-string#1]
Hi! 

While researching about a possibility to achieve this with a SMT (Already wanted to start to implement my own one) I stumbled over your repo. 

I didn't see any license info in your repo or files therefore I'm not sure If I can use it in my setup. Is it Apache 2? 

Also it would be awesome to get it officially onto confluent hub (https://www.confluent.io/hub/) did you thought about that already? 

BR
an0r0c

**Comment by yashmayya** [comment]
Hi @an0r0c! I've added an MIT license to this repo and you can feel free to use this however you please. Although, after writing this SMT, I discovered a similar one which already exists on Hub ([docs](https://jcustenborder.github.io/kafka-connect-documentation/projects/kafka-connect-transform-common/transformations/BytesToString.html) , [hub](https://www.confluent.io/hub/jcustenborder/kafka-connect-transform-common)) - and supports additional features such as taking a list of fields to transform and charset to use while transforming.

**Comment by christian-edelsbrunner** [comment]
Hi, thanks that one on confluent hub works for my purpose :)
